# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PPC_Device_Daemon": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://durapensa.github.io/pico_pi_controller/"

git_url = "https://github.com/durapensa/pico_pi_controller/tree/main/"

def custom_doc_links(name): return None
