# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"logger": "60_ppcc.ipynb",
         "log_txn": "60_ppcc.ipynb",
         "PwrLedFlicker": "50_ppdd.ipynb",
         "PPCcHandler": "50_ppdd.ipynb",
         "goodbye": "60_ppcc.ipynb",
         "i2c_event_handler": "50_ppdd.ipynb",
         "main": "60_ppcc.ipynb",
         "empty": "50_ppdd.ipynb",
         "pause": "50_ppdd.ipynb",
         "hostname": "50_ppdd.ipynb",
         "bosmang": "50_ppdd.ipynb",
         "cmd_code": "50_ppdd.ipynb",
         "tcp_address": "60_ppcc.ipynb",
         "REG_NAME": "60_ppcc.ipynb",
         "REG_INT": "60_ppcc.ipynb",
         "connect_ppdd": "60_ppcc.ipynb"}

modules = ["core.py",
           "ppdd.py",
           "ppcc.py"]

doc_url = "https://durapensa.github.io/pico_pi_controller/"

git_url = "https://github.com/durapensa/pico_pi_controller/tree/main/"

def custom_doc_links(name): return None
