# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['PwrLedFlicker', 'REG_NAME', 'empty', 'pause', 'hostname', 'bosmang', 'cmd_code']

# Cell
from platform import node
from os import getloadavg, environ
from sys import byteorder
from threading import Thread
import time
import pigpio
import atexit

from CircuitPython_pico_pi_common.codes import *

REG_NAME = { }
for name, code in REG_CODE.items():
    REG_NAME[int.from_bytes(code, byteorder=byteorder)]=name

environ['TZ']="America/New_York"
time.tzset()

empty = bytearray(0)
pause = bytearray(1)
hostname = bytearray(node(),'utf-8')
bosmang = bytearray(int(1).to_bytes(1,byteorder))
cmd_code = bytearray([122,0x13,0x03]) # FLICKER,0x13,3 seconds

class PwrLedFlicker(Thread):
    def __init__(self, duration):
        Thread.__init__(self)
        self.duration = duration

    def run(self):
        with open('/sys/class/leds/led1/brightness', 'w') as sys_pwr_led:
            for x in range(self.duration*2):
                sys_pwr_led.write('0')
                sys_pwr_led.flush()
                time.sleep(0.1)
                sys_pwr_led.write('1')
                sys_pwr_led.flush()
                time.sleep(0.4)
        sys_pwr_led.close()